// <auto-generated />
using System;
using System.Collections.Generic;
using BrandInspector.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BrandInspector.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260330103114_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BrandInspector.Models.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("BrandInspector.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BrandInspector.Models.Brand", b =>
                {
                    b.OwnsOne("BrandInspector.Models.BrandConfig", "BrandConfig", b1 =>
                        {
                            b1.Property<Guid>("BrandId")
                                .HasColumnType("uuid");

                            b1.PrimitiveCollection<List<string>>("Colors")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.PrimitiveCollection<List<string>>("Fonts")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.PrimitiveCollection<List<double>>("Sizes")
                                .IsRequired()
                                .HasColumnType("double precision[]");

                            b1.HasKey("BrandId");

                            b1.ToTable("Brands");

                            b1
                                .ToJson("BrandConfig")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("BrandId");
                        });

                    b.Navigation("BrandConfig")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
